apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "secret-store.rbacRoleName" .Values.rbac.roleName }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
