name: Helm Lint & Security Checks

env:
  CHECKOV_SKIP_CHECKS: --skip-check CKV_K8S_21
  HELM_CLI_VERSION: 3.18.4

on:
  pull_request:
    branches: ['**']
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - 'charts/**'

jobs:
  helm-security-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
          
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: ${{ env.HELM_CLI_VERSION }}

      - name: Setup Python for Checkov
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Checkov
        run: pip install -r requirements.txt

      - name: Add Helm repositories
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update

      - name: Build chart dependencies
        run: helm dependency build

      - name: Lint Helm chart
        run: helm lint .

      - name: Render Helm templates
        run: helm template . > rendered.yaml

      - name: Run Checkov on Helm chart
        run: checkov -d . --framework helm $CHECKOV_SKIP_CHECKS

      - name: Run Checkov on rendered Kubernetes manifests
        run: checkov -f rendered.yaml --framework kubernetes $CHECKOV_SKIP_CHECKS

      - name: Upload rendered manifests as artifact
        if: failure()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
        with:
          name: rendered-manifests
          path: rendered.yaml
          retention-days: 7